### ISSUE TITLE
Incident update loads forever

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/CoCeMoCl#24] opened 2019-02-20 08:38 UTC
GIVEN the incidents' view is open
WHEN I drag down the list
THEN a loading indicator appears and never goes away

Is dragging down implemented? Does it trigger a scope request?

**Comment by fs1** [comment] 2019-02-20 14:56
I can reproduce this issue with my Samsung Galaxy XCover 3 (SM-G389F) and GeoClient 1.1.0.

**Comment by robo-w** [comment] 2019-02-20 17:59
will be fixed in >1.1.1

**Closed by robo-w** 2019-02-20 17:59 UTC
Labels: bug, feedback

**Comment by fs1** [comment] 2019-02-21 08:31
works for me now (GeoClient 1.1.1)
